name: Native Image
on:
  push:
  pull_request:
jobs:
  unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - run: gu install native-image
      - run: jabba install graal-custom@19.3=tgz+https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.0/graalvm-ce-java11-darwin-amd64-19.3.0.tar.gz
      - name: sbt cli/graalvm-native-image:packageBin
        run: |
        jabba use graal-custom@19.3
        sbt cli/graalvm-native-image:packageBin
      - uses: actions/upload-artifact@master
        with:
          name: scalafmt
          path: scalafmt-cli/target/graalvm-native-image/cli
